name: Upstream-sync

on:
    schedule:
        - cron: '*/30 * * * *' # every 30 minutes
    workflow_dispatch: # on button click

jobs:
    sync:
        runs-on: ubuntu-latest

        steps:
              - name: Checkout repository
                uses: actions/checkout@v3
                with:
                  fetch-depth: 0
    
              - name: Merge upstream changes
                run: |
                  git fetch upstream main
                  git checkout master
                  git merge upstream/main --strategy-option=ours || true
                  git rm .\cn_dicts\tencent.dict.yaml
    
              - name: Commit and push changes
                env:
                run: |
                    git config --global user.name "GitHub Actions"
                    git config --global user.email "actions@github.com"
                    git add --all
                    git commit -m "Auto: Upstream sync $(date +'%Y-%m-%d')" || echo "No changes to commit"
                    git push origin master